name: AwsLambdaWorkflow

on:
  push:
    branches: ["test"]

jobs :
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: '22.x'  #specify the version of node
       - name: Configure AWS Credentials
         uses: aws-action/configure-aws-credentials@v1 # Setup the Credential
         with:
           aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
           aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
           aws-region: ap-south-1 #AWS server region
       - name: npm install
         env:
           CI: true
         run: |
           npm ci
       - name: deploy
         run: |
           zip -j deploy.zip ./* #Zip the code as we know lambda function accept the zip file
           aws lambda update-function-code --function-name=interviewsite --zip-file=fileb://deploy.zip
    
    
